engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- app/assets/javascripts/bootstrap.js
- app/assets/stylesheets/bootstrap.css
- lib/**/*
- spec/**/*
#because we plan on removing this file
- 'app/helpers/users_helper.rb'
- "**/vendor/**/*"
