language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - rbx-3.69
  - jruby
  - jruby-head
  
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3.69
    - rvm: 2.4 # https://bugs.ruby-lang.org/issues/13537